name: Docker Hub Deploy

on:
  push:
    branches:
      - main     # Deploy automático
      - dev      # Build e teste, mas sem push

jobs:
  docker-build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: eduborges0101/aifinance_api_instance
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "🛠️ Buildando imagem Docker..."
          docker build \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg DB_HOST=${{ secrets.DB_HOST }} \
            --build-arg DB_PORT=${{ secrets.DB_PORT }} \
            --build-arg DB_USER=${{ secrets.DB_USER }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg DB_NAME=${{ secrets.DB_NAME }} \
            -t $IMAGE_NAME:$IMAGE_TAG \
            .
      

      - name: Run container test
        run: |
          echo "🚀 Testando a imagem..."
          docker run --rm \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            $IMAGE_NAME:$IMAGE_TAG python -c "print('✅ Container OK!')"
      

      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main' && success()
        run: |
          echo "📦 Enviando imagem para o Docker Hub..."
          docker push $IMAGE_NAME:$IMAGE_TAG
